### ISSUE TITLE
Image dockerfile/nginx not found

### ISSUE THREAD

**Issue by serchavalos** [vfarcic/continuous-deployment#1]
Hello!

Following your tutorial "[Continuous deployment: implemenation](http://technologyconversations.com/2014/12/08/continuous-deployment-implementation/)"

I couldn't load nginx with `systemctl` when I tried to run `sudo systemctl start nginx.service`

`systemctl status nginx` prompted me this:

```
core@localhost ~ $ systemctl status nginx
● nginx.service - nginx
   Loaded: loaded (/etc/systemd/system/nginx.service; enabled)
   Active: failed (Result: exit-code) since Fri 2015-04-24 09:08:22 UTC; 7min ago
 Main PID: 1527 (code=exited, status=1/FAILURE)

Apr 24 09:08:20 localhost docker[1517]: Pulling repository dockerfile/nginx
Apr 24 09:08:21 localhost systemd[1]: Started nginx.
Apr 24 09:08:21 localhost docker[1517]: 2015/04/24 09:08:21 Error: image dockerfile/nginx not found
Apr 24 09:08:21 localhost docker[1527]: Unable to find image 'dockerfile/nginx' locally
Apr 24 09:08:21 localhost docker[1527]: Pulling repository dockerfile/nginx
Apr 24 09:08:22 localhost systemd[1]: nginx.service: main process exited, code=exited, status=1/FAILURE
Apr 24 09:08:22 localhost docker[1527]: 2015/04/24 09:08:22 Error: image dockerfile/nginx not found
Apr 24 09:08:22 localhost docker[1536]: Error response from daemon: No such container: nginx
Apr 24 09:08:22 localhost docker[1536]: 2015/04/24 09:08:22 Error: failed to stop one or more containers
Apr 24 09:08:22 localhost systemd[1]: Unit nginx.service entered failed state.
```

Is it suppose to be "[dockerana/nginx](https://registry.hub.docker.com/u/dockerana/nginx/)" instead? If so, let me know I will make the pull request

PS: Great tutorial by the way!

**Comment by serchavalos** [comment]
Actually it seems that it worked by replacing `dockerfile/nginx` to `nginx` only. Is it right?

Thanks,

**Comment by vfarcic** [comment]
You're right. It should be nginx (without dockerfile/).

Docker recently changed naming convention and removed dockerfile/ from names of official images. In some cases there are even more changes like dockerfile/mongodb became mongo (without db).

Anyways, I forgot to update this repo (there are probably quite a few more that should be updated as well) until you brought it to my attention. I just modified it. Thank you for the tip.
